
name: garmin-sheets-cron

on:
  schedule:
    # Example: every 15 minutes 05:00–09:00 PT, hourly otherwise
    - cron: "*/15 12-16 * * *"   # 05:00–09:00 PT (converted to UTC; adjust for DST as needed)
    - cron: "0 * * * *"          # hourly
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install garth garminconnect python-dotenv gspread google-auth

      - name: Run Garmin -> Google Sheets
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          GARMIN_MFA_CODE: ${{ secrets.GARMIN_MFA_CODE }}
          LOCAL_TZ: America/Los_Angeles

          # Google Sheets auth (choose one)
          GOOGLE_SERVICE_ACCOUNT_FILE: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_FILE }} # optional, path inside repo or runner
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }} # recommended: paste JSON into a secret

          GOOGLE_SHEETS_SPREADSHEET_ID: ${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }}
          GOOGLE_SHEETS_WORKSHEET_TITLE: Garmin Daily

          WINDOW_DAYS: "5"
          INCLUDE_TODAY: "1"
        run: |
          python garmin-sheets-daily.py
