name: garmin-sheets-cron

on:
  schedule:
    # 05:00–09:59 US/Pacific every 15 minutes.
    # UTC note: During PDT (UTC-7) this is 12-16 UTC. During PST (UTC-8) adjust to 13-17 UTC.
    - cron: "*/15 12-16 * * *"
    # Hourly all day
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install garth garminconnect python-dotenv gspread google-auth

      # Optional: restore the Garmin token-store directory from a secret.
      # See garmin-tokenstore-gha-snippet.yml for how to generate the secret.
      - name: Restore Garmin token-store directory
        if: ${{ secrets.GARMIN_TOKEN_STORE_TGZ_B64 != '' }}
        shell: bash
        run: |
          mkdir -p "$RUNNER_TEMP/garmin_tokens"
          echo "${{ secrets.GARMIN_TOKEN_STORE_TGZ_B64 }}" | base64 -d > "$RUNNER_TEMP/garmin_tokens.tgz"
          tar -C "$RUNNER_TEMP/garmin_tokens" -xzf "$RUNNER_TEMP/garmin_tokens.tgz"

      - name: Run Garmin to Google Sheets
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          GARMIN_TOKEN_STORE: ${{ runner.temp }}/garmin_tokens/.garmin_tokens
          LOCAL_TZ: America/Los_Angeles

          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GOOGLE_SHEETS_SPREADSHEET_ID: ${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }}
          GOOGLE_SHEETS_WORKSHEET_TITLE: Garmin Daily

          WINDOW_DAYS: "5"
          INCLUDE_TODAY: "1"
        run: |
          python garmin-sheets-daily.py
