
# --- GitHub Actions snippet to restore a token-store directory ---
# 1) Create tokens locally (with MFA), which writes to ~/.garmin_tokens (a DIRECTORY):
#    - Run the script once locally with GARMIN_EMAIL/PASSWORD set.
#    - Verify: ls ~/.garmin_tokens  (you should see multiple files, not just one)
# 2) Pack and encode the directory:
#    tar -C ~ -czf garmin_tokens.tgz .garmin_tokens
#    base64 garmin_tokens.tgz > garmin_tokens.tgz.b64
#    Copy the contents into a GitHub Secret named GARMIN_TOKEN_STORE_TGZ_B64.
#
# 3) In your workflow, add before running the script:
- name: Restore Garmin token-store directory
  shell: bash
  run: |
    mkdir -p "$RUNNER_TEMP/garmin_tokens"
    echo "${{ secrets.GARMIN_TOKEN_STORE_TGZ_B64 }}" | base64 -d > "$RUNNER_TEMP/garmin_tokens.tgz"
    tar -C "$RUNNER_TEMP/garmin_tokens" -xzf "$RUNNER_TEMP/garmin_tokens.tgz"
  # Set env for the run step:
  #   GARMIN_TOKEN_STORE: ${{ runner.temp }}/garmin_tokens/.garmin_tokens
