name: Sync Garmin to Notion

on:
  schedule:
    # Hourly, year-round (at :00)
    - cron: '0 * * * *'

    # Every 15 min from 5:00–9:59 AM **local** during PDT (Apr–Oct)
    - cron: '15,30,45 12-16 * 4-10 *'

    # Every 15 min from 5:00–9:59 AM **local** during PST (Nov–Mar)
    - cron: '15,30,45 13-17 * 11,12,1-3 *'
  workflow_dispatch:
env:
  TZ: 'America/Montreal'
  GARMIN_TOKEN_DIR: '/home/runner/.garth'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run script
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          NOTION_PR_DB_ID: ${{ secrets.NOTION_PR_DB_ID }}
          NOTION_STEPS_DB_ID: ${{ secrets.NOTION_STEPS_DB_ID }}
          NOTION_SLEEP_DB_ID: ${{ secrets.NOTION_SLEEP_DB_ID }}
          TZ: 'America/Montreal'
        run: |
          python garmin-store-token.py
          python garmin-2fa-login.py
          python garmin-activities.py
          python personal-records.py
          python daily-steps.py
          python sleep-data.py
